//! A note an agent harvests from a closed session (AD-404, R26 Q2/Q3), as
//! keeper stores it, and the one act that marks it reviewed.
//!
//! A steward's harvest turn writes candidate notes into her own harvest
//! session, under `artifacts/knowledge/<the closed session's folder>/`
//! (R140). What the model wrote is never what makes a note trusted: the
//! host stamps `generated` with the agent and its host and `human_reviewed:
//! false` over whatever the model said, keeps `type` to the drive's own
//! registry, and refuses a `verified` review, a person's name as a source's
//! author, a source outside the closed session, and a note a person could
//! not read whole (S-32). So a harvested note never claims a person.
//!
//! The tick is a person's, through their keeper ([`review`]): it is written
//! into the vault's copy only, never into the candidate the agent's host
//! also writes (R139), as the canonical `verified` block keeper's OKF reader
//! reads back. What it proves is that a reader's keeper committed it, not
//! that the person typed it (R28 S-31).
//!
//! Pure: the host reads the registry and the sources and writes the bytes.

use std::collections::BTreeSet;

use crate::notes::frontmatter::{FieldValue, Frontmatter};
use crate::notes::okf::{self, ActorKind, Verification};

/// Where in a session harvested notes live, session-relative.
pub const KNOWLEDGE_DIR: &str = "artifacts/knowledge";

/// The most a knowledge note holds, in bytes, as stored (R28 S-32).
pub const MAX_NOTE_BYTES: usize = 64 * 1024;

/// The most a vault copy of a knowledge note holds that keeper reads whole
/// and writes a review into: a note at [`MAX_NOTE_BYTES`] with the review
/// blocks of the persons who tick it (`verified: - by: human:<localpart>`,
/// `at:`, and `human_reviewed`) — about 330 bytes each at a Matrix
/// localpart's longest, so 16 KiB holds some fifty. A promotion or a tick
/// whose copy would hold more is refused, so every copy keeper published
/// can still be read whole and have its review changed.
pub const MAX_REVIEWED_BYTES: usize = MAX_NOTE_BYTES + 16 * 1024;

/// The `type` a note gets when the drive's registry does not hold the one
/// it named.
pub const DEFAULT_TYPE: &str = "Note";

/// The drive's OKF type registry, drive-relative.
pub const REGISTRY: &str = ".okf/registry/types.md";

/// The key AD-390's label wrapper reads.
pub const HUMAN_REVIEWED: &str = "human_reviewed";

/// Whether the session-relative `landed` is a knowledge note's place.
pub fn is_note(landed: &str) -> bool {
    landed
        .strip_prefix(KNOWLEDGE_DIR)
        .is_some_and(|rest| rest.starts_with('/'))
}

/// The closed session's folder name a note at the session-relative
/// `landed` was harvested from: `artifacts/knowledge/<slug>/<note>.md`.
/// `None` for a note with no such folder above it.
pub fn source_slug(landed: &str) -> Option<&str> {
    let rest = landed.strip_prefix(KNOWLEDGE_DIR)?.strip_prefix('/')?;
    let (slug, note) = rest.split_once('/')?;
    (!slug.is_empty() && !note.is_empty()).then_some(slug)
}

/// The actor an agent's note is generated by: `agent:<agent>@<host>`.
pub fn agent_actor(agent: &str, host: &str) -> String {
    format!("agent:{agent}@{host}")
}

/// The agent and the host an `agent:<agent>@<host>` actor names.
pub fn signer_of(actor: &str) -> Option<(&str, &str)> {
    let (agent, host) = actor.trim().strip_prefix("agent:")?.split_once('@')?;
    (!agent.is_empty() && !host.is_empty()).then_some((agent, host))
}

/// The localpart a person's review is signed with (`human:<localpart>`),
/// from their Matrix user id; `None` for a string that is not one.
pub fn reviewer(user_id: &str) -> Option<String> {
    <&matrix_sdk::ruma::UserId>::try_from(user_id)
        .ok()
        .map(|user| user.localpart().to_owned())
}

/// Every `type` the drive's registry lists: the backticked first cell of
/// each table row of `.okf/registry/types.md`.
pub fn registry_types(text: &str) -> BTreeSet<String> {
    text.lines()
        .filter_map(|line| {
            let cell = line.trim().strip_prefix('|')?.split('|').next()?.trim();
            let name = cell.strip_prefix('`')?.strip_suffix('`')?;
            (!name.is_empty()).then(|| name.to_owned())
        })
        .collect()
}

/// What the host stamps a harvested note with.
#[derive(Debug, Clone, Copy)]
pub struct Harvest<'a> {
    /// `agent:<agent>@<host>` ([`agent_actor`]).
    pub actor: &'a str,
    /// When, RFC 3339.
    pub at: &'a str,
    /// The drive's registry ([`registry_types`]).
    pub types: &'a BTreeSet<String>,
    /// The sessions zone's folder inside the drive: `60-sessions`.
    pub sessions_subfolder: &'a str,
    /// The closed session, zone-relative: `archive/<year>/<folder>`.
    pub source_session: &'a str,
}

/// A note as the host stores it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stamped {
    /// The bytes to store.
    pub text: String,
    /// Each source as written, with the file it names, zone-relative, which
    /// must be there.
    pub sources: Vec<(String, String)>,
}

/// Why a harvested note is not stored. Each says that nothing was written.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum KnowledgeRefusal {
    #[error("a knowledge note holds at most 64 KiB, so a person reviewing it can read all of it; this one would be {bytes} bytes, and nothing was written.")]
    TooLarge { bytes: usize },
    #[error("verified is a person's review, which their keeper writes when they tick the note; an agent's note never carries it, so nothing was written.")]
    Verified,
    #[error(
        "{actor} names a person, and an agent's note never speaks for one; nothing was written."
    )]
    ClaimsPerson { actor: String },
    #[error("{resource} is not inside {session}, the session this note was harvested from: a source is a file of that session by its path from the drive's root, or log/<chunk>#<line id>. Nothing was written.")]
    SourceOutside { resource: String, session: String },
    #[error("{resource} is not in {session}, the session this note was harvested from; nothing was written.")]
    SourceMissing { resource: String, session: String },
    #[error("a knowledge note lives at artifacts/knowledge/<the closed session's folder>/<note>.md; nothing was written.")]
    NoFolder,
    #[error("{slug} is no closed session of this drive, so a note harvested from it has nothing to stand on; nothing was written.")]
    NoSuchSession { slug: String },
    #[error("`{line}` is metadata keeper cannot read for certain, and a note keeper signs carries nothing it cannot read; nothing was written.")]
    Unreadable { line: String },
    #[error("sources is a block list of entries, each with one resource; `{line}` is not one, so nothing was written.")]
    SourcesUnreadable { line: String },
}

/// Whether a key the frontmatter scanner recorded is one a YAML reader
/// reads as the same key: no escape, flow or indicator syntax in it.
fn plain_key(key: &str) -> bool {
    !key.starts_with([
        '?', '-', ':', ',', '&', '*', '!', '|', '>', '\'', '"', '%', '@', '`', '<',
    ]) && !key.contains(['\\', '{', '}', '[', ']'])
}

/// `text`, an agent's candidate note, as the host stores it: `generated`
/// is `harvest.actor` at `harvest.at` and `human_reviewed` is `false`
/// whatever the model wrote, a `type` the registry does not hold is
/// [`DEFAULT_TYPE`], and a note with no `status` is a `draft`. Every source
/// is checked to lie inside the closed session, and its file is handed back
/// for the host to find.
///
/// # Errors
/// [`KnowledgeRefusal::Unreadable`] for a frontmatter line the scanner
/// skips (an explicit `? key`, a flow map, an anchor, a merge key) or a key
/// spelt with escapes or indicators — its meaning cannot be established, so
/// it might be a review — [`KnowledgeRefusal::Verified`] for any
/// `verified`/`verified_by` key, [`KnowledgeRefusal::SourcesUnreadable`]
/// for a `sources` list [`okf::strict_sources`] cannot read whole,
/// [`KnowledgeRefusal::ClaimsPerson`] for a person as a source's author,
/// [`KnowledgeRefusal::SourceOutside`] for a source outside the closed
/// session, and [`KnowledgeRefusal::TooLarge`] when the stored bytes would
/// pass [`MAX_NOTE_BYTES`]. Unknown keys a reader can name are kept.
pub fn stamp(text: &str, harvest: &Harvest) -> Result<Stamped, KnowledgeRefusal> {
    let (fm, _) = Frontmatter::parse(text);
    if let Some(line) = fm
        .unclaimed_lines()
        .first()
        .map(|line| line.trim())
        .or_else(|| fm.keys().find(|key| !plain_key(key)))
    {
        return Err(KnowledgeRefusal::Unreadable {
            line: line.to_owned(),
        });
    }
    if fm.count("verified") > 0 || fm.count("verified_by") > 0 {
        return Err(KnowledgeRefusal::Verified);
    }
    let supplied =
        okf::strict_sources(&fm).map_err(|line| KnowledgeRefusal::SourcesUnreadable { line })?;
    let doc = okf::read(&fm);
    if let Some(actor) = supplied
        .iter()
        .filter_map(|source| source.author.as_deref())
        .find(|actor| okf::actor_kind(actor) == ActorKind::Person)
    {
        return Err(KnowledgeRefusal::ClaimsPerson {
            actor: actor.to_owned(),
        });
    }
    let sources = supplied
        .iter()
        .map(|source| {
            source_file(&source.resource, harvest).map(|file| (source.resource.clone(), file))
        })
        .collect::<Result<Vec<_>, _>>()?;

    let newline = if fm.raw_block().contains("\r\n") {
        "\r\n"
    } else {
        "\n"
    };
    let mut out = text.to_owned();
    if !doc
        .doc_type
        .as_ref()
        .is_some_and(|kind| harvest.types.contains(kind))
    {
        out = Frontmatter::remove_all_in(&out, "type");
        out = Frontmatter::set_in(&out, "type", FieldValue::Str(DEFAULT_TYPE.to_owned()));
    }
    let generated = format!(
        "generated:{newline}  by: {}{newline}  at: {}{newline}",
        harvest.actor, harvest.at
    );
    out = Frontmatter::replace_lines_in(
        &out,
        "generated",
        &generated,
        &["type", "title", "description", "sources"],
    );
    out = Frontmatter::remove_all_in(&out, HUMAN_REVIEWED);
    out = Frontmatter::set_after_in(
        &out,
        &["generated"],
        HUMAN_REVIEWED,
        FieldValue::Bool(false),
    );
    if doc.status.is_none() {
        out = Frontmatter::set_after_in(
            &out,
            &[HUMAN_REVIEWED],
            "status",
            FieldValue::Str("draft".to_owned()),
        );
    }
    if out.len() > MAX_NOTE_BYTES {
        return Err(KnowledgeRefusal::TooLarge { bytes: out.len() });
    }
    Ok(Stamped { text: out, sources })
}

/// The file `resource` names, zone-relative, when it lies inside the closed
/// session: drive-relative under it, or `log/<chunk>#<line id>` of its log.
fn source_file(resource: &str, harvest: &Harvest) -> Result<String, KnowledgeRefusal> {
    let outside = || KnowledgeRefusal::SourceOutside {
        resource: resource.to_owned(),
        session: harvest.source_session.to_owned(),
    };
    let plain =
        |part: &str| !part.is_empty() && part != "." && part != ".." && !part.contains('\\');
    let resource = resource.trim();
    if let Some(rest) = resource.strip_prefix("log/") {
        let (chunk, line) = rest.split_once('#').ok_or_else(outside)?;
        if !plain(chunk) || chunk.contains('/') || line.trim().is_empty() {
            return Err(outside());
        }
        return Ok(format!("{}/log/{chunk}", harvest.source_session));
    }
    let mut parts = resource.split('/');
    for want in harvest
        .sessions_subfolder
        .split('/')
        .chain(harvest.source_session.split('/'))
        .filter(|part| !part.is_empty())
    {
        if parts.next() != Some(want) {
            return Err(outside());
        }
    }
    let rest: Vec<&str> = parts.collect();
    if rest.is_empty() || !rest.iter().all(|part| plain(part)) {
        return Err(outside());
    }
    Ok(format!("{}/{}", harvest.source_session, rest.join("/")))
}

/// The person `person` (a Matrix localpart) ticking (`reviewed`) or
/// unticking a note: the tick appends `verified: - by: human:<person>, at:
/// <at>` and sets `human_reviewed: true`; the untick removes that person's
/// entries and sets `human_reviewed` to whether another person's review is
/// left. A tick already there keeps its time. Whatever spelling the reviews
/// had — `verified: true` beside `verified_by`, bare actors, a key twice —
/// a write leaves them canonical (R139). Every other byte stays.
pub fn review(text: &str, person: &str, at: &str, reviewed: bool) -> String {
    let actor = format!("human:{person}");
    let (fm, _) = Frontmatter::parse(text);
    let doc = okf::read(&fm);
    let had = doc.verified.iter().any(|entry| entry.by == actor);
    let canonical = doc.verified_shape != okf::VerifiedShape::Simplified
        && fm.count("verified") <= 1
        && fm.count("verified_by") == 0;
    let mut entries: Vec<Verification> = doc.verified;
    let out = if reviewed && had && canonical {
        text.to_owned()
    } else {
        if reviewed && !had {
            entries.push(Verification {
                by: actor,
                at: Some(at.to_owned()),
            });
        } else if !reviewed {
            entries.retain(|entry| entry.by != actor);
        }
        okf::write_verified(text, &entries)
    };
    let by_person = entries
        .iter()
        .any(|entry| entry.actor_kind() == ActorKind::Person);
    if fm.count(HUMAN_REVIEWED) == 1 && fm.as_bool(HUMAN_REVIEWED) == Some(by_person) {
        return out;
    }
    let out = Frontmatter::remove_all_in(&out, HUMAN_REVIEWED);
    Frontmatter::set_after_in(
        &out,
        &["verified", "generated"],
        HUMAN_REVIEWED,
        FieldValue::Bool(by_person),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agents::label::okf_label_facts;
    use crate::bots::tools::okf_facts;

    const AT: &str = "2026-10-06T09:00:00Z";

    fn types() -> BTreeSet<String> {
        registry_types(
            "# OKF type registry\n\n| `type` | what | class |\n|---|---|---|\n| `Note` | thinking | `td:Note` |\n| `Reference` | a digest | x |\n",
        )
    }

    fn harvest(types: &BTreeSet<String>) -> Harvest<'_> {
        Harvest {
            actor: "agent:tola-grey@electra",
            at: AT,
            types,
            sessions_subfolder: "60-sessions",
            source_session: "archive/2026/2026-10-05-taxes",
        }
    }

    const CANDIDATE: &str = "---\ntype: Reference\ntitle: What the tax office wants\ndescription: The three papers.\nsources:\n  - id: s1\n    resource: 60-sessions/archive/2026/2026-10-05-taxes/artifacts/answer.md\n    title: The answer\n  - id: s2\n    resource: log/2026-10-05.electra.1.jsonl#01J5ZZZZZZZZZZZZZZZZZZZZZZ\n---\n\nBring the PIT-37, the receipts and the ID.\n";

    /// 95.5 acceptance 3 (Q3, §3 row 30): keeper's two readers read a
    /// stamped note as an agent's and unreviewed — `okf_facts` names its
    /// agent generator and no reviewer, and the label wrapper's fact is
    /// `human_reviewed: false`, which keeps a read of it at `agent`
    /// integrity. After a person's tick both say a person reviewed it.
    #[test]
    fn keeper_reads_a_harvested_note_as_unreviewed() {
        let types = types();
        let stored = stamp(CANDIDATE, &harvest(&types)).expect("stored").text;
        let facts = okf_facts(&stored).expect("frontmatter");
        assert_eq!(
            facts.generated_by.as_deref(),
            Some("agent:tola-grey@electra")
        );
        assert_eq!(facts.generated_actor, Some(ActorKind::Agent));
        assert_eq!(facts.verified_by, None);
        assert!(!facts.human_reviewed);
        assert_eq!(okf_label_facts(&stored).human_reviewed, Some(false));

        let ticked = review(&stored, "tgorka", AT, true);
        let facts = okf_facts(&ticked).expect("frontmatter");
        assert!(facts.human_reviewed);
        assert_eq!(facts.verified_by.as_deref(), Some("human:tgorka"));
        assert_eq!(facts.verified_actor, Some(ActorKind::Person));
        assert_eq!(okf_label_facts(&ticked).human_reviewed, Some(true));
    }

    /// 95.5 acceptance 1, the pure half: whatever the model wrote in
    /// `generated` and `human_reviewed`, the stored note says the agent on
    /// its host made it and nobody reviewed it; a type the registry lacks
    /// is a `Note`; a `verified` review, a person as a source's author and
    /// a source outside the closed session are refused; the size cap is on
    /// the stored bytes, exactly 64 KiB stored and one more refused.
    #[test]
    fn the_host_stamps_what_a_model_cannot_be_trusted_to_say() {
        let types = types();
        let harvest = harvest(&types);
        let forged = CANDIDATE
            .replace("type: Reference", "type: Gospel")
            .replace(
                "---\n\nBring",
                "generated: {by: human:tgorka, at: 2020-01-01}\nhuman_reviewed: true\n---\n\nBring",
            );
        let stamped = stamp(&forged, &harvest).expect("stored");
        let doc = okf::read(&Frontmatter::parse(&stamped.text).0);
        assert_eq!(
            doc.generated
                .as_ref()
                .map(|g| (g.by.as_str(), g.at.as_deref())),
            Some(("agent:tola-grey@electra", Some(AT)))
        );
        assert_eq!(doc.doc_type.as_deref(), Some(DEFAULT_TYPE));
        assert_eq!(doc.status.as_deref(), Some("draft"));
        assert_eq!(
            Frontmatter::parse(&stamped.text).0.as_bool(HUMAN_REVIEWED),
            Some(false)
        );
        assert!(stamped
            .text
            .ends_with("---\n\nBring the PIT-37, the receipts and the ID.\n"));
        assert_eq!(
            stamped
                .sources
                .iter()
                .map(|(_, file)| file.as_str())
                .collect::<Vec<_>>(),
            [
                "archive/2026/2026-10-05-taxes/artifacts/answer.md",
                "archive/2026/2026-10-05-taxes/log/2026-10-05.electra.1.jsonl"
            ]
        );
        // A registry type is kept as written.
        let kept = stamp(CANDIDATE, &harvest).expect("stored");
        assert_eq!(
            okf::read(&Frontmatter::parse(&kept.text).0)
                .doc_type
                .as_deref(),
            Some("Reference")
        );

        for verified in [
            "verified:\n  - by: human:tgorka\n    at: 2026-10-06\n",
            "verified: true\n",
            "verified_by: human:tgorka\n",
        ] {
            let with = CANDIDATE.replace("sources:\n", &format!("{verified}sources:\n"));
            assert_eq!(stamp(&with, &harvest), Err(KnowledgeRefusal::Verified));
        }
        let person = CANDIDATE.replace("    title: The answer\n", "    author: user:marta\n");
        assert_eq!(
            stamp(&person, &harvest),
            Err(KnowledgeRefusal::ClaimsPerson {
                actor: "user:marta".to_owned()
            })
        );
        for outside in [
            "60-sessions/archive/2026/2026-10-05-other/artifacts/answer.md",
            "60-sessions/archive/2026/2026-10-05-taxes",
            "60-sessions/archive/2026/2026-10-05-taxes/../2026-10-05-other/a.md",
            "10-notes/taxes.md",
            "https://example.com/pit-37",
            "log/../agent.toml#x",
            "log/2026-10-05.electra.1.jsonl",
        ] {
            let with = CANDIDATE.replace(
                "60-sessions/archive/2026/2026-10-05-taxes/artifacts/answer.md",
                outside,
            );
            assert!(
                matches!(stamp(&with, &harvest), Err(KnowledgeRefusal::SourceOutside { resource, .. }) if resource == outside),
                "{outside}"
            );
        }

        let base = stamp(CANDIDATE, &harvest).expect("stored").text.len();
        let padded = |extra: usize| format!("{CANDIDATE}{}", "x".repeat(extra));
        let exact = stamp(&padded(MAX_NOTE_BYTES - base), &harvest).expect("exactly 64 KiB");
        assert_eq!(exact.text.len(), MAX_NOTE_BYTES);
        assert_eq!(
            stamp(&padded(MAX_NOTE_BYTES - base + 1), &harvest),
            Err(KnowledgeRefusal::TooLarge {
                bytes: MAX_NOTE_BYTES + 1
            })
        );
    }

    /// R95K-09: a review keeper's scanner cannot name — an explicit `?`
    /// key, a flow map, a merge key, an anchor, an escaped key — is
    /// refused like a `verified` it can, so no YAML reader finds a
    /// model-written review in a stored note; a quoted or repeated
    /// `verified` is a `verified`. Unknown metadata a reader can name is
    /// kept as written.
    #[test]
    fn a_review_keeper_cannot_name_is_refused() {
        let types = types();
        let harvest = harvest(&types);
        let with = |head: &str| CANDIDATE.replace("sources:\n", &format!("{head}sources:\n"));
        for unreadable in [
            "? verified\n: [{by: human:tgorka}]\n",
            "{verified: [human:tgorka]}\n",
            "<<: {verified: true}\n",
            "&a verified: true\n",
            "\"verif\\u0069ed\": true\n",
        ] {
            assert!(
                matches!(
                    stamp(&with(unreadable), &harvest),
                    Err(KnowledgeRefusal::Unreadable { .. })
                ),
                "{unreadable}"
            );
        }
        for verified in [
            "\"verified\": true\n",
            "'verified_by': human:tgorka\n",
            "verified: []\nverified: [human:tgorka]\n",
        ] {
            assert_eq!(
                stamp(&with(verified), &harvest),
                Err(KnowledgeRefusal::Verified),
                "{verified}"
            );
        }
        let unknown = "project: taxes\nextra: {a: 1}\n";
        let stored = stamp(&with(unknown), &harvest).expect("stored").text;
        assert!(stored.contains(unknown), "{stored}");
    }

    /// R95K-10: every source the note supplies is read before it is stored
    /// or the note is refused — a flow list of maps (which the tolerant
    /// reader would silently drop, person and all), an item with no
    /// resource, a key twice, a nested map, a non-scalar value, an inline
    /// value, `sources` twice. A bare item and an item opened by a lone
    /// `-` are read and checked.
    #[test]
    fn every_source_is_read_or_the_note_is_refused() {
        let types = types();
        let harvest = harvest(&types);
        let a = "60-sessions/archive/2026/2026-10-05-taxes/artifacts/answer.md";
        let note =
            |sources: &str| format!("---\ntype: Reference\ntitle: T\n{sources}---\n\nBody.\n");
        for sources in [
            format!("sources: [{{resource: {a}, author: human:tgorka}}]\n"),
            format!("sources: {{resource: {a}}}\n"),
            format!("sources: {a}\n"),
            "sources:\n  - id: s1\n    title: no resource\n".to_owned(),
            format!("sources:\n  - resource: {a}\n    resource: {a}\n"),
            format!("sources:\n  - resource: {a}\n    meta:\n      author: human:tgorka\n"),
            format!("sources:\n  - resource: {a}\n    author: [human:tgorka]\n"),
            format!("sources:\n  - resource: {a}\nsources:\n  - resource: {a}\n"),
        ] {
            assert!(
                matches!(
                    stamp(&note(&sources), &harvest),
                    Err(KnowledgeRefusal::SourcesUnreadable { .. })
                ),
                "{sources}"
            );
        }
        let file = "archive/2026/2026-10-05-taxes/artifacts/answer.md";
        for sources in [
            format!("sources:\n  - {a}\n"),
            format!("sources:\n  -\n    resource: {a}\n    author: agent:tola-grey@electra\n"),
        ] {
            let stored = stamp(&note(&sources), &harvest).expect("stored");
            assert_eq!(
                stored.sources,
                [(a.to_owned(), file.to_owned())],
                "{sources}"
            );
        }
    }

    /// R95K-16: ticking a copy whose review is in the legacy spelling —
    /// `verified: true` beside `verified_by`, here with CRLF line ends and a
    /// comment — keeps that review and writes it canonical: one `verified`
    /// block, no `verified_by`, `human_reviewed: true`, the comment and the
    /// line ends kept. With two legacy reviewers, the untick of one leaves
    /// the other, canonical, and the note still reviewed by a person.
    #[test]
    fn a_legacy_review_is_written_canonical() {
        let legacy = "---\r\ntype: Note\r\ntitle: Taxes\r\n# kept: a comment\r\nverified: true\r\nverified_by: human:tgorka\r\nhuman_reviewed: false\r\n---\r\n\r\nBody.\r\n";
        let ticked = review(legacy, "tgorka", AT, true);
        let (fm, _) = Frontmatter::parse(&ticked);
        let doc = okf::read(&fm);
        assert_eq!(
            doc.verified,
            [Verification {
                by: "human:tgorka".to_owned(),
                at: None
            }]
        );
        assert_eq!(doc.verified_shape, okf::VerifiedShape::Canonical);
        assert_eq!(fm.count("verified_by"), 0);
        assert_eq!(fm.as_bool(HUMAN_REVIEWED), Some(true));
        assert!(ticked.contains("# kept: a comment\r\n"), "{ticked:?}");
        assert!(ticked.ends_with("---\r\n\r\nBody.\r\n"), "{ticked:?}");
        assert!(!ticked.replace("\r\n", "").contains('\n'), "{ticked:?}");

        let two = "---\ntype: Note\nverified: true\nverified_by: [human:marta, human:tgorka]\nhuman_reviewed: true\n---\n\nBody.\n";
        let unticked = review(two, "tgorka", AT, false);
        let (fm, _) = Frontmatter::parse(&unticked);
        let doc = okf::read(&fm);
        assert_eq!(
            doc.verified
                .iter()
                .map(|v| v.by.as_str())
                .collect::<Vec<_>>(),
            ["human:marta"]
        );
        assert_eq!(doc.verified_shape, okf::VerifiedShape::Canonical);
        assert_eq!(fm.count("verified_by"), 0);
        assert_eq!(fm.as_bool(HUMAN_REVIEWED), Some(true));
    }

    /// R95K2-09: a review written as one map — a flow map, or `by:` and
    /// `at:` indented under `verified:` with no `-` — is read, and ticking
    /// it as the same person rewrites it as the one block list a writer
    /// leaves, reviewer and time kept, every other byte as it was.
    #[test]
    fn a_single_map_review_is_written_as_a_list() {
        let list = "verified:\n  - by: human:tgorka\n    at: 2026-10-01T08:00:00Z\n";
        for single in [
            "verified: {by: human:tgorka, at: 2026-10-01T08:00:00Z}\n",
            "verified:\n  by: human:tgorka\n  at: 2026-10-01T08:00:00Z\n",
        ] {
            let note = |verified: &str| {
                format!(
                    "---\ntype: Note\ntitle: Taxes\n{verified}human_reviewed: true\n---\n\nBody.\n"
                )
            };
            assert_eq!(
                review(&note(single), "tgorka", AT, true),
                note(list),
                "{single}"
            );
        }
    }

    /// R95K2-05: a source's author is read as YAML reads it, escapes and
    /// all: `"\u0068uman:tgorka"` and `"\x75ser:marta"` name a person to any
    /// YAML reader, so they are refused as one; an escape YAML does not
    /// define is a source keeper cannot read for certain, refused as such.
    #[test]
    fn an_escaped_author_is_read_as_yaml_reads_it() {
        let types = types();
        let harvest = harvest(&types);
        let with = |author: &str| {
            CANDIDATE.replace(
                "    title: The answer\n",
                &format!("    author: {author}\n"),
            )
        };
        for (author, actor) in [
            ("\"\\u0068uman:tgorka\"", "human:tgorka"),
            ("\"\\x75ser:marta\"", "user:marta"),
            ("\"\\U00000068uman:tgorka\"", "human:tgorka"),
        ] {
            assert_eq!(
                stamp(&with(author), &harvest),
                Err(KnowledgeRefusal::ClaimsPerson {
                    actor: actor.to_owned()
                }),
                "{author}"
            );
        }
        for unreadable in ["\"\\qhuman:tgorka\"", "\"human:\"tgorka\""] {
            assert!(
                matches!(
                    stamp(&with(unreadable), &harvest),
                    Err(KnowledgeRefusal::SourcesUnreadable { .. })
                ),
                "{unreadable}"
            );
        }
        let tool = stamp(&with("\"agent:tola\\u002dgrey@electra\""), &harvest).expect("stored");
        assert!(tool
            .text
            .contains("author: \"agent:tola\\u002dgrey@electra\""));
    }

    /// 95.5 acceptance 7 (Q17): a person's tick appends their canonical
    /// `verified` entry and sets `human_reviewed: true`, leaving every
    /// other byte, and keeper's OKF reader reads it back; the untick takes
    /// exactly that entry out again and sets `false`; another person's
    /// review survives both, and a second tick changes nothing.
    #[test]
    fn only_a_person_marks_a_note_reviewed() {
        let types = types();
        let stored = stamp(CANDIDATE, &harvest(&types)).expect("stored").text;

        let ticked = review(&stored, "tgorka", AT, true);
        let doc = okf::read(&Frontmatter::parse(&ticked).0);
        assert_eq!(
            doc.verified,
            [Verification {
                by: "human:tgorka".to_owned(),
                at: Some(AT.to_owned())
            }]
        );
        assert_eq!(doc.verified_shape, okf::VerifiedShape::Canonical);
        assert_eq!(
            Frontmatter::parse(&ticked).0.as_bool(HUMAN_REVIEWED),
            Some(true)
        );
        let expected = stored
            .replace(
                "  at: 2026-10-06T09:00:00Z\nhuman_reviewed: false\n",
                "  at: 2026-10-06T09:00:00Z\nverified:\n  - by: human:tgorka\n    at: 2026-10-06T09:00:00Z\nhuman_reviewed: true\n",
            );
        assert_eq!(ticked, expected, "every other byte stays");
        assert_eq!(review(&ticked, "tgorka", "2027-01-01", true), ticked);

        let unticked = review(&ticked, "tgorka", AT, false);
        assert_eq!(unticked, stored, "the untick restores the bytes");

        let by_marta = review(&ticked, "marta", AT, true);
        let without_tgorka = review(&by_marta, "tgorka", AT, false);
        let doc = okf::read(&Frontmatter::parse(&without_tgorka).0);
        assert_eq!(
            doc.verified
                .iter()
                .map(|v| v.by.as_str())
                .collect::<Vec<_>>(),
            ["human:marta"]
        );
        assert_eq!(
            Frontmatter::parse(&without_tgorka)
                .0
                .as_bool(HUMAN_REVIEWED),
            Some(true)
        );
    }
}
