//! Which bundle a path belongs to, and whether the config excludes it — the
//! drive's own answers, rule for rule, as its tools give them.
//!
//! A pattern is read the way the drive's tools read it (proved by
//! `tests/fixtures/okf/match.jsonl`, generated by running them):
//! - ending in `/` or `/**`, it is a **literal prefix**: `a/**` holds every
//!   path that starts `a/`, and nothing in the prefix is a wildcard — so
//!   `60-sessions/**/workspace/**` excludes only paths that start with those
//!   very characters (the config's own comment says so, and epic 95's Q9
//!   found it: no real session's workspace is excluded by it);
//! - without a wildcard, the whole path, exactly;
//! - with a wildcard and a `/`, the whole path, where `*` is any run of
//!   characters, `/` included, and `?` is any one;
//! - with a wildcard and no `/`, the file name alone, by the same rule.
//!
//! `[`, `]` and `\` are ordinary characters, and the match is case-sensitive.

use super::config::{Bundle, Config};

/// Whether `rel` matches `pattern`.
pub fn matches(pattern: &str, rel: &str) -> bool {
    if let Some(prefix) = pattern.strip_suffix("**").filter(|p| p.ends_with('/')) {
        return rel.starts_with(prefix);
    }
    if pattern.ends_with('/') {
        return rel.starts_with(pattern);
    }
    if !pattern.contains(['*', '?']) {
        return rel == pattern;
    }
    if pattern.contains('/') {
        wildcard(pattern.as_bytes(), rel.as_bytes())
    } else {
        let name = rel.rsplit('/').next().unwrap_or(rel);
        wildcard(pattern.as_bytes(), name.as_bytes())
    }
}

/// `*` and `?` over bytes, every other byte literal; `?` takes one
/// character, which is one UTF-8 sequence.
fn wildcard(pattern: &[u8], text: &[u8]) -> bool {
    let (mut p, mut t) = (0, 0);
    let mut star: Option<(usize, usize)> = None;
    while t < text.len() {
        match pattern.get(p) {
            Some(b'*') => {
                star = Some((p, t));
                p += 1;
                continue;
            }
            Some(b'?') => {
                p += 1;
                t += char_len(text[t]);
                continue;
            }
            Some(&c) if c == text[t] => {
                p += 1;
                t += 1;
                continue;
            }
            _ => {}
        }
        match star {
            Some((sp, st)) => {
                let st = st + char_len(text[st]);
                star = Some((sp, st));
                p = sp + 1;
                t = st;
            }
            None => return false,
        }
    }
    pattern[p..].iter().all(|&c| c == b'*')
}

/// The length of the UTF-8 sequence `first` starts.
fn char_len(first: u8) -> usize {
    match first {
        0xF0..=0xFF => 4,
        0xE0..=0xEF => 3,
        0xC0..=0xDF => 2,
        _ => 1,
    }
}

/// Whether `config` keeps `rel` out of every bundle: a guide never is, and
/// anything one of the `exclude` patterns matches is.
pub fn is_excluded(config: &Config, rel: &str) -> bool {
    !config.guides.iter().any(|guide| guide == rel)
        && config.exclude.iter().any(|pattern| matches(pattern, rel))
}

/// The innermost bundle `rel` lies inside: the root bundle holds every
/// path, any other one the paths under its folder.
pub fn bundle_for<'c>(config: &'c Config, rel: &str) -> Option<&'c Bundle> {
    config
        .bundles
        .iter()
        .filter(|bundle| {
            bundle.is_root()
                || rel
                    .strip_prefix(bundle.path.as_str())
                    .is_some_and(|rest| rest.starts_with('/'))
        })
        .max_by_key(|bundle| {
            if bundle.is_root() {
                0
            } else {
                bundle.path.len() + 1
            }
        })
}

/// Whether `config` excludes every path under folder `dir` (drive-relative,
/// without a trailing `/`), so a walk need never enter it: no guide lies
/// under it, and a pattern that matches `dir/` matches every path below —
/// a literal prefix, or a wildcard pattern holding a `/` whose last
/// character is `*`. Anything else is decided file by file.
pub fn excludes_folder(config: &Config, dir: &str) -> bool {
    let folder = format!("{dir}/");
    !config.guides.iter().any(|guide| guide.starts_with(&folder))
        && config.exclude.iter().any(|pattern| {
            let whole = pattern.ends_with('/')
                || pattern.ends_with("/**")
                || (pattern.contains('/') && pattern.ends_with('*'));
            whole && matches(pattern, &folder)
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A folder is skipped whole only when every path under it is
    /// excluded: not when a guide lies in it, not for a pattern that could
    /// match the folder's name and nothing below it.
    #[test]
    fn a_folder_is_excluded_only_when_everything_under_it_is() {
        let config = Config {
            okf_version: "0.2".to_owned(),
            bundles: Vec::new(),
            exclude: ["inbox/**", "work/clients/*", "x/dir?", "*.md", "tmp/"]
                .map(str::to_owned)
                .to_vec(),
            guides: vec!["inbox/README.md".to_owned()],
            no_index: Vec::new(),
            listed: Vec::new(),
        };
        assert!(!excludes_folder(&config, "inbox"));
        assert!(excludes_folder(&config, "work/clients/acme"));
        assert!(excludes_folder(&config, "tmp"));
        assert!(excludes_folder(&config, "tmp/deep"));
        assert!(!excludes_folder(&config, "x/dir"));
        assert!(!excludes_folder(&config, "notes"));
        assert!(!excludes_folder(&config, "work"));
    }
}
