/**
 * The tool-call row: what the model read, what it was refused, and what it was
 * not told (Epic 61, Story 61.11, FR-388, FR-389, FR-391, NFR-49).
 *
 * Five things are asserted here that nothing else in the tree asserts:
 *
 * 1. **The bound is on the collapsed row, and only when there was one.** A
 *    result the model was told was truncated says so before anybody expands
 *    anything; a whole result carries no notice at all, because a notice on
 *    every row teaches a reader to skip it.
 * 2. **A refusal is distinguishable without colour** — `data-refused`, a glyph
 *    of its own, a dashed rule and the word "Refused", none of which is a hue
 *    (`DESIGN.md`'s `Never`).
 * 3. **OKF provenance is read, never inferred.** A note generated by a model
 *    and reviewed by nobody must not read as person-verified, and a read with
 *    no frontmatter must not sprout provenance it never had.
 * 4. **The DOM is bounded too.** An 80 kB result is a scroll-killing text node;
 *    the row renders a clipped prefix and says whose clip it was.
 * 5. **No live region.** Rows land one per tool mid-stream, and a transcript
 *    that announces each one talks over the answer.
 */
import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import {
  BOT_TOOL_ARGUMENTS_LABEL,
  BOT_TOOL_DOM_CHARS,
  BOT_TOOL_GRANT_DENIED_LABEL,
  BOT_TOOL_REFUSED_LABEL,
  BOT_TOOL_RESULT_LABEL,
  BotToolCall,
  botToolCallCaption,
  botToolClipNotice,
} from "@/components/bots/bot-tool-call";
import type { BotToolCallVm } from "@/lib/ipc/client";

/** A read that returned a whole small file. */
function call(overrides: Partial<BotToolCallVm> = {}): BotToolCallVm {
  return {
    id: "call-1",
    requestedName: "drive_read",
    name: "read",
    displayPath: "work/notes/a.md",
    refusal: null,
    grantDenied: false,
    arguments: '{"path":"work/notes/a.md"}',
    result: "# Notes\nthe body the model read",
    outcome: "text",
    bytes: 1200,
    truncatedAtBytes: null,
    ofBytes: null,
    entries: null,
    truncatedAtEntries: null,
    ofEntries: null,
    okf: null,
    ...overrides,
  };
}

/** The one disclosure on screen. */
function row(): HTMLElement {
  return screen.getAllByRole("button")[0] as HTMLElement;
}

describe("BotToolCall", () => {
  it("renders one collapsed disclosure naming the verb, the path and the outcome", () => {
    render(<BotToolCall count={1} calls={[call()]} />);

    const disclosure = row();
    expect(disclosure).toHaveAttribute("aria-expanded", "false");
    // The verb and the path in a person's words, not `drive_read` and an id.
    expect(disclosure).toHaveTextContent("read work/notes/a.md");
    expect(disclosure).toHaveTextContent("read 1.2 kB");
    // Collapsed means collapsed: neither half of the exchange is in the DOM.
    expect(screen.queryByText(BOT_TOOL_ARGUMENTS_LABEL)).not.toBeInTheDocument();
    expect(screen.queryByText(BOT_TOOL_RESULT_LABEL)).not.toBeInTheDocument();
  });

  it("expands onto what it asked for and what the model was told", () => {
    render(<BotToolCall count={1} calls={[call()]} />);

    fireEvent.click(row());

    const disclosure = row();
    expect(disclosure).toHaveAttribute("aria-expanded", "true");
    // `aria-expanded` alone is a dead end for a screen reader: the region it
    // names must exist while it is named.
    const controls = disclosure.getAttribute("aria-controls");
    expect(controls).not.toBeNull();
    expect(document.getElementById(controls as string)).toBeInTheDocument();
    expect(screen.getByText(BOT_TOOL_ARGUMENTS_LABEL)).toBeInTheDocument();
    expect(screen.getByText('{"path":"work/notes/a.md"}')).toBeInTheDocument();
    expect(screen.getByText(BOT_TOOL_RESULT_LABEL)).toBeInTheDocument();
    expect(screen.getByText(/the body the model read/)).toBeInTheDocument();

    fireEvent.click(row());
    expect(row()).toHaveAttribute("aria-expanded", "false");
  });

  it("discloses a bounded result on the collapsed row, in bytes", () => {
    render(
      <BotToolCall
        count={1}
        calls={[call({ bytes: 65_536, truncatedAtBytes: 65_536, ofBytes: 1_258_291 })]}
      />,
    );

    // The same disclosure `render_result` puts in the text the model reads.
    expect(row()).toHaveTextContent("truncated at 65 kB of 1.2 MB");
  });

  it("discloses a bounded listing in entries", () => {
    render(
      <BotToolCall
        count={1}
        calls={[
          call({
            name: "list",
            requestedName: "drive_list",
            displayPath: "work",
            outcome: "entries",
            bytes: null,
            entries: 200,
            truncatedAtEntries: 200,
            ofEntries: 1240,
          }),
        ]}
      />,
    );

    expect(row()).toHaveTextContent("200 entries");
    expect(row()).toHaveTextContent("truncated at 200 entries of 1240");
  });

  it("says nothing about truncation when the result was whole", () => {
    const { container } = render(<BotToolCall count={1} calls={[call()]} />);

    fireEvent.click(row());
    expect(container.textContent).not.toMatch(/truncated/);
  });

  it("marks a refusal by shape and words, never by colour alone", () => {
    const reason = "keeper's grant for this bot permits reading, not writing.";
    const { container } = render(
      <BotToolCall
        count={1}
        calls={[
          call({
            name: "write",
            requestedName: "drive_write",
            outcome: "refused",
            refusal: reason,
            bytes: null,
            result: "",
          }),
        ]}
      />,
    );

    const item = container.querySelector('[data-slot="bot-tool-call"]');
    // Four channels, none of them a hue: the flag, the word, the glyph, the rule.
    expect(item).toHaveAttribute("data-refused", "true");
    expect(row()).toHaveTextContent(BOT_TOOL_REFUSED_LABEL);
    expect(container.querySelector(".lucide-ban")).not.toBeNull();
    expect(item?.className).toContain("border-dashed");
    // The refusing layer's own sentence, not keeper's paraphrase of it.
    expect(screen.getByText(reason)).toBeInTheDocument();
  });

  it("keeps a successful row free of every refusal channel", () => {
    const { container } = render(<BotToolCall count={1} calls={[call()]} />);

    const item = container.querySelector('[data-slot="bot-tool-call"]');
    expect(item).toHaveAttribute("data-refused", "false");
    expect(container.querySelector(".lucide-ban")).toBeNull();
    expect(item?.className).not.toContain("border-dashed");
    expect(container.textContent).not.toMatch(new RegExp(BOT_TOOL_REFUSED_LABEL));
  });

  it("names a grant's refusal as the grant's, because that one is the person's to widen", () => {
    render(
      <BotToolCall
        count={1}
        calls={[
          call({
            outcome: "refused",
            refusal: "No grant covers work/private.",
            grantDenied: true,
            bytes: null,
            result: "",
          }),
        ]}
      />,
    );

    expect(row()).toHaveTextContent(BOT_TOOL_GRANT_DENIED_LABEL);
  });

  it("renders a note's OKF type and says when no person reviewed it", () => {
    const { container } = render(
      <BotToolCall
        count={1}
        calls={[
          call({
            okf: {
              docType: "note",
              generatedBy: "claude/opus-5",
              generatedActor: "a tool",
              verifiedBy: "bot:indexer",
              verifiedActor: "a bot",
              humanReviewed: false,
              sentence:
                "Provenance: OKF type note, generated by claude/opus-5 (a tool), checked but not by a person.",
            },
          }),
        ]}
      />,
    );

    const provenance = container.querySelector('[data-slot="bot-tool-provenance"]');
    expect(provenance).toHaveTextContent("OKF type note");
    expect(provenance).toHaveTextContent("generated by claude/opus-5 (a tool)");
    // The load-bearing negative: a model-checked note must not read as
    // person-verified.
    expect(provenance).toHaveTextContent("checked by a bot, not by a person");
    expect(container.textContent).not.toMatch(/reviewed by a person/);
  });

  it("names the person who reviewed a note, when one did", () => {
    const { container } = render(
      <BotToolCall
        count={1}
        calls={[
          call({
            okf: {
              docType: "decision",
              generatedBy: null,
              generatedActor: null,
              verifiedBy: "human:alice",
              verifiedActor: "a person",
              humanReviewed: true,
              sentence: "Provenance: OKF type decision, reviewed by a person (human:alice).",
            },
          }),
        ]}
      />,
    );

    const provenance = container.querySelector('[data-slot="bot-tool-provenance"]');
    expect(provenance).toHaveTextContent("reviewed by a person (human:alice)");
  });

  it("says a note nobody reviewed is a note nobody reviewed", () => {
    const { container } = render(
      <BotToolCall
        count={1}
        calls={[
          call({
            okf: {
              docType: "note",
              generatedBy: null,
              generatedActor: null,
              verifiedBy: null,
              verifiedActor: null,
              humanReviewed: false,
              sentence: "Provenance: OKF type note, nobody has reviewed it.",
            },
          }),
        ]}
      />,
    );

    expect(container.querySelector('[data-slot="bot-tool-provenance"]')).toHaveTextContent(
      "nobody has reviewed it",
    );
  });

  it("invents no provenance for a read that carried none", () => {
    const { container } = render(<BotToolCall count={1} calls={[call({ okf: null })]} />);

    expect(container.querySelector('[data-slot="bot-tool-provenance"]')).toBeNull();
    expect(container.textContent).not.toMatch(/OKF/);
    expect(container.textContent).not.toMatch(/reviewed/);
  });

  it("does not put a 64 kB result in the DOM", () => {
    const body = "x".repeat(65_536);
    const { container } = render(
      <BotToolCall count={1} calls={[call({ result: body, bytes: 65_536 })]} />,
    );

    fireEvent.click(row());

    expect(screen.getByText(botToolClipNotice(BOT_TOOL_DOM_CHARS, 65_536))).toBeInTheDocument();
    // The whole row, chrome included, stays within a couple of screenfuls.
    expect(container.textContent?.length ?? 0).toBeLessThan(BOT_TOOL_DOM_CHARS * 2);
    expect(container.textContent).not.toContain(body);
  });

  it("keeps arriving rows out of every live region", () => {
    const { container } = render(
      <BotToolCall
        count={3}
        calls={[
          call({ id: "a" }),
          call({ id: "b", displayPath: "work/notes/b.md" }),
          call({ id: "c", displayPath: "work/notes/c.md" }),
        ]}
      />,
    );

    expect(container.querySelector("[aria-live]")).toBeNull();
    expect(screen.queryAllByRole("status")).toHaveLength(0);
    expect(screen.queryAllByRole("log")).toHaveLength(0);
    expect(screen.queryAllByRole("alert")).toHaveLength(0);
    expect(screen.getAllByRole("listitem")).toHaveLength(3);
  });

  it("falls back to the stored count for a conversation replayed without detail", () => {
    render(<BotToolCall count={2} calls={[]} />);

    expect(screen.getByText(botToolCallCaption(2))).toBeInTheDocument();
    expect(screen.queryAllByRole("button")).toHaveLength(0);
  });

  it("renders nothing for a turn that called no tools", () => {
    const { container } = render(<BotToolCall count={0} />);

    expect(container).toBeEmptyDOMElement();
  });
});
