// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BbctlPhase } from "./BbctlPhase";

/**
 * A snapshot of a `bbctl` self-hosted-bridge run, streamed over the run `Channel`
 * (Story 6.7, FR-29, NFR secret containment).
 *
 * The single view model the webview renders for the whole run: the `network_id`
 * being run, the current [`BbctlPhase`], an optional per-phase `message`, and the
 * verbatim `error` (failure phase). Carries **only** non-secret render data — the
 * account's Beeper token is never read into a VM, and no raw `bbctl` log line
 * reaches the UI (only recognized phase markers project a snapshot).
 */
export type BbctlProgressVm = { 
/**
 * The stable network id being run (e.g. `"signal"`).
 */
networkId: string, 
/**
 * The current run phase.
 */
phase: BbctlPhase, 
/**
 * An optional per-phase message line, or `null`.
 */
message: string | null, 
/**
 * `bbctl`'s verbatim error message (capped, non-secret), present in the
 * `Failure` phase, else `null`.
 */
error: string | null, };
