// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The guided-install block of the bbctl availability VM (Story 6.7): ordered human
 * `steps` and a `docs_url` to the Beeper self-host documentation.
 */
export type BbctlInstallVm = { 
/**
 * The ordered install steps (rendered as a numbered list — may repeat prose,
 * so the frontend keys them by index).
 */
steps: Array<string>, 
/**
 * The Beeper self-host docs URL.
 */
docsUrl: string, };
