// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The phase of a `bbctl` self-hosted-bridge run (Story 6.7, FR-29).
 *
 * A log-free projection of the `bbctl register`/`run` progression, rendered as a
 * distinct stepper state. The frontend switches on this phase; only recognized
 * prose markers ever produce a phase (unrecognized `bbctl` output is dropped —
 * there is no path from a raw log line to the UI). `run` is launch-and-leave: on
 * the started marker the run resolves at [`BbctlPhase::Success`] leaving the
 * daemon alive and unsupervised (v1.x — no restart policy, no log viewer).
 * Serializes to its camelCase name — the frontend wire contract.
 */
export type BbctlPhase = "checking" | "registering" | "starting" | "running" | "success" | "failure";
