// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The live connection health of a bridged session (Story 6.5, FR-28, NFR-6,
 * UX-DR8/UX-DR11).
 *
 * A pure, per-session state — keyed by `(account_id, network_id)` — driven by the
 * bridge's management-room notices (real-time via the running sync) with a bounded
 * bot-ping liveness fallback. Distinct from the *setup* [`BridgeStatus`] (which is a
 * one-shot discovery result): this is the live signal that a logged-in session went
 * silent (device unlinked, token expired) or recovered. Serializes to its camelCase
 * name — the frontend wire contract. The frontend renders the dot / state-word / red
 * edge / roll-up / banner as pure projections of this one enum and never re-derives it.
 */
export type BridgeHealth = "healthy" | "degraded" | "disconnected";
