// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The discovered setup/login status of a bridged Network on an Account's
 * homeserver (Story 6.2, FR-25, AD-16).
 *
 * Derived once, per Account, from the merged three-source discovery pass
 * (`thirdparty/protocols` + known-bot MXID probe + bot-DM/portal room scan) by
 * the pure `merge_discovery` function. It is the *setup* state, not live
 * connection health — live health (degraded / disconnected, 60 s surfacing) is
 * Story 6.5 and stays a separate placeholder. Serializes to its camelCase name —
 * the frontend wire contract.
 */
export type BridgeStatus = "loggedIn" | "notLoggedIn" | "configured";
