// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User input submitted into a running bridge login (Story 6.3, FR-26).
 *
 * A deserialize-in input VM pushed into the driver by `bridge_login_submit`: a
 * flow choice (from the `ChoosingMethod` phase) or a map of field id → entered
 * value (from the `CodeEntry` phase). Entered values are carried straight into the
 * transport's submit body and never logged. Serialized as an internally tagged
 * enum so the frontend can switch on `kind`.
 */
export type BridgeLoginInput = { "kind": "chooseFlow", 
/**
 * The chosen flow id (matches a [`LoginFlowVm::id`]).
 */
flowId: string, } | { "kind": "fields", 
/**
 * The entered values, keyed by [`LoginFieldVm::id`].
 */
values: { [key in string]: string }, };
