// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeHealth } from "./BridgeHealth";

/**
 * One bridged session's live health, keyed by `(account_id, network_id)` (Story
 * 6.5, FR-28).
 *
 * Carries **only** non-secret render data: the opaque keeper `account_id`, the stable
 * machine `network_id` (the `protocol.id`, the row/conversation join key — never the
 * display label), the resolved display `network_name` for banner/card copy, the live
 * [`BridgeHealth`], the `last_checked_ms` timestamp (ms since the Unix epoch), and an
 * optional `detail` carrying the bot's verbatim reason (trimmed, length-capped, no
 * tokens or session material). Never a bot MXID, token, or session material.
 */
export type BridgeSessionHealthVm = { 
/**
 * Opaque keeper account id this session belongs to (part of the join key).
 */
accountId: string, 
/**
 * The stable machine `network_id` (`protocol.id`), the room/conversation join
 * key — never the display label.
 */
networkId: string, 
/**
 * The Network's display name for the card / banner copy (e.g. `"WhatsApp"`).
 */
networkName: string, 
/**
 * The live connection health.
 */
health: BridgeHealth, 
/**
 * When the session was last checked: ms since the Unix epoch (UTC).
 */
lastCheckedMs: number, 
/**
 * The bot's verbatim reason (trimmed, length-capped, no tokens/session material),
 * or `null` — populated on a disconnected/degraded notice, cleared on recovery.
 */
detail: string | null, };
