// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeLoginPhase } from "./BridgeLoginPhase";
import type { LoginFieldVm } from "./LoginFieldVm";
import type { LoginFlowVm } from "./LoginFlowVm";

/**
 * A snapshot of a native bridge login flow, streamed over the login `Channel`
 * (Story 6.3, FR-26, AD-16, NFR secret containment).
 *
 * The single view model the webview renders for the whole login, mirroring
 * [`VerificationFlowVm`]'s phase-plus-optional-payload shape. Carries **only**
 * non-secret render data: the `network_id` being linked, the current
 * [`BridgeLoginPhase`], a per-phase `instruction` line, a pre-rendered `qr_svg`
 * (QR phase), the `qr_refreshed` flag (a fresh QR during an active QR phase), the
 * `fields` to render (code-entry phase), the `flows` to pick from (choosing-method
 * phase), and the bridge's verbatim `error` (failure phase). The account's Matrix
 * access token is used only as an HTTP Bearer header inside the transport and
 * **never** appears here — no token, cookie, or session material crosses IPC.
 */
export type BridgeLoginVm = { 
/**
 * The stable network id being linked (e.g. `"whatsapp"`), joined to the 6.1
 * catalog by the frontend for glyph/name.
 */
networkId: string, 
/**
 * The current login phase.
 */
phase: BridgeLoginPhase, 
/**
 * A per-phase instruction line (e.g. "Scan this QR with WhatsApp on your
 * phone."), or `null`.
 */
instruction: string | null, 
/**
 * The pre-rendered QR-code SVG string, present in the `Qr` phase, else `null`.
 */
qrSvg: string | null, 
/**
 * `true` when a fresh QR replaced an earlier one during an active `Qr` phase
 * (drives the subtle "QR refreshed" note); `false` otherwise.
 */
qrRefreshed: boolean, 
/**
 * The non-secret field descriptors to render, populated in the `CodeEntry`
 * phase (empty otherwise).
 */
fields: Array<LoginFieldVm>, 
/**
 * The selectable login methods, populated in the `ChoosingMethod` phase (empty
 * otherwise).
 */
flows: Array<LoginFlowVm>, 
/**
 * The bridge's verbatim error message (or keeper's honest reason), present in
 * the `Failure` phase, else `null`.
 */
error: string | null, };
