// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BadgeStyle } from "./BadgeStyle";
import type { RiskTier } from "./RiskTier";

/**
 * One connectable bridged Network in the data-driven Bridges catalog (Story 6.1,
 * FR-42, Epic 6 addendum §2).
 *
 * A pure projection of a *surfaced* tier's network entry from `risk-tiers.json`:
 * the stable `network_id`, display `name`, `glyph` initials, the resolved
 * [`RiskTier`], its display `tier_label`, the [`BadgeStyle`], whether connecting
 * `requires_ack`, and the acknowledgment `ack_copy` (present iff `requires_ack`).
 * The catalog is account-agnostic — the frontend keys a card per Network × Account
 * — and carries no health, session, or bridge state (health is Story 6.5; discovery
 * is Story 6.2). All risk/badge/ack copy is data, never hardcoded in TypeScript.
 */
export type BridgeNetworkVm = { 
/**
 * The stable network identifier (e.g. `"whatsapp"`), from the data file.
 */
networkId: string, 
/**
 * The Network's display name (e.g. `"WhatsApp"`).
 */
name: string, 
/**
 * The glyph initials rendered in the card avatar (e.g. `"WA"`).
 */
glyph: string, 
/**
 * The resolved risk tier.
 */
tier: RiskTier, 
/**
 * The tier's display label (e.g. `"Maintenance-heavy"`), from the data file.
 */
tierLabel: string, 
/**
 * The badge style driving the card's risk-tier Badge.
 */
badgeStyle: BadgeStyle, 
/**
 * Whether connecting this Network requires an explicit acknowledgment (the
 * volatile / conditional gate).
 */
requiresAck: boolean, 
/**
 * The acknowledgment copy shown in the connect gate, present iff
 * `requires_ack`, else `null`. Sourced from the tier's `acknowledgment` field.
 */
ackCopy: string | null, };
