// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeSessionHealthVm } from "./BridgeSessionHealthVm";

/**
 * The full current bridge-session health snapshot, streamed as a whole-snapshot
 * batch over the health subscription's `Channel` (Story 6.5, FR-28, AD-8).
 *
 * Sessions are few, so there is no diff protocol: each batch carries the complete
 * set of monitored (logged-in) sessions across every account, and the frontend
 * replaces its keyed map wholesale. Emitted on subscribe (the bootstrap snapshot),
 * then **only on a real per-session state change** (diffed) — no periodic re-emit
 * noise, matching the `NetworksSnapshot` cadence contract.
 */
export type BridgeHealthSnapshot = { 
/**
 * Every monitored (logged-in) session's live health, across all accounts.
 */
sessions: Array<BridgeSessionHealthVm>, };
