// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionStatus } from "./ConnectionStatus";

/**
 * A batch delivered over the connection-status subscription's `Channel` (AD-8).
 *
 * The status is a scalar snapshot, so each batch carries the full current
 * [`ConnectionStatus`] — inherently idempotent, safe to re-subscribe. The stream
 * opens with the current mapped status, then emits on change (deduped).
 */
export type ConnectionStatusBatch = { 
/**
 * The current connectivity status.
 */
status: ConnectionStatus, };
