// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The account's live connectivity, as mapped from the SDK `SyncService` state
 * (FR-8/FR-9, UX-DR10, UX-DR18, AD-8).
 *
 * A Rust-authoritative signal streamed over the connection-status channel:
 * `Online` when the `SyncService` is `Running`, `Offline` for every other state
 * (`Idle`, `Terminated`, `Error`, `Offline`). The frontend renders the offline
 * pill and the "Queued" send caption as pure projections of this one status —
 * no timeline item is invented or mutated. Only the enum tag crosses IPC.
 */
export type ConnectionStatus = "online" | "offline";
