// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a job is in its life (AD-C1).
 */
export type CopyJobState = "copying" | "verifying" | "done" | "failed" | "cancelled";
