// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file's outcome, flattened for the wire.
 */
export type CopyEntryVm = { 
/**
 * Source-relative, so the report reads as the user's own tree.
 */
path: string, bytes: number, 
/**
 * `copied` | `identical` | `collision` | `failed`.
 */
outcome: string, 
/**
 * Present only for `failed`.
 */
reason: string | null, };
