// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One per-Network coupling caveat — a behavior that connecting a Network couples
 * in (Story 8.2, FR-44). A pure read-only projection of `coupling-caveats.json`:
 * the stable `network_id` this caveat applies to, the human-readable `text` shown
 * inline at the per-Chat Incognito toggle, and `applies_to`, a machine tag naming
 * the coupled surface (e.g. `"read-receipts"`). All caveat copy is data — none is
 * authored in TypeScript. Joined to the open room's Network by `network_id` on the
 * frontend; an uncoupled or native (null-network) room shows no caveat.
 */
export type CouplingCaveatVm = { 
/**
 * The stable network identifier this caveat applies to (e.g. `"whatsapp"`).
 */
networkId: string, 
/**
 * The human-readable caveat text, from the data file.
 */
text: string, 
/**
 * A machine tag naming the coupled surface (e.g. `"read-receipts"`).
 */
appliesTo: string, };
