// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single demo item carried in snapshot/diff batches. Placeholder payload
 * that exercises the snapshot-then-diff channel pattern end-to-end.
 */
export type DemoItem = { 
/**
 * Stable item id.
 */
id: string, 
/**
 * Display label.
 */
label: string, };
