// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeStatus } from "./BridgeStatus";

/**
 * One discovered bridged Network for an Account (Story 6.2, FR-25, AD-16).
 *
 * Carries only the stable `network_id` (joined to the 6.1 [`BridgeNetworkVm`]
 * catalog on the frontend for glyph/name/tier badge/ack copy) and the derived
 * [`BridgeStatus`]. Only catalog-gated Networks appear here — a discovered
 * protocol with no catalog entry is logged and dropped, never surfaced.
 * Serializes camelCase — the frontend wire contract.
 */
export type DiscoveredBridgeVm = { 
/**
 * The stable network identifier (e.g. `"whatsapp"`), joined to the 6.1
 * catalog by the frontend for presentation.
 */
networkId: string, 
/**
 * The Network's derived setup/login status.
 */
status: BridgeStatus, };
