// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of a network egress destination (Story 11.2, NFR-11).
 *
 * Classifies each entry in the [`EgressEndpointVm`] list the Settings → About
 * surface renders so the frontend can label it honestly without re-deriving the
 * classification. `Homeserver` is an account's Matrix homeserver; `Beeper` is the
 * `api.beeper.com` login/service endpoint present exactly when a Beeper account
 * exists; `Update` is the signed-update endpoint the app checks. Serializes to
 * `"homeserver" | "beeper" | "update"`.
 */
export type EgressKind = "homeserver" | "beeper" | "update";
