// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptionStatus } from "./EncryptionStatus";

/**
 * A batch delivered over the encryption-status subscription's `Channel` (AD-8).
 *
 * The status is a scalar snapshot, so each batch carries the full current
 * [`EncryptionStatus`] — inherently idempotent, safe to re-subscribe. The stream
 * opens with the current mapped status, then emits on change (deduped).
 */
export type EncryptionStatusBatch = { 
/**
 * The current device-verification status.
 */
status: EncryptionStatus, };
