// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportPhase } from "./ExportPhase";

/**
 * A progress (or terminal) batch streamed over the export subscription's
 * `Channel` (Story 5.5, FR-35, UX-DR11).
 *
 * Carries **only** non-secret progress data: the job's `exportId`, its current
 * [`ExportPhase`], the running message/media counts, the written `outputPaths`
 * (populated on `Completed`), and a human `error` string on `Failed`. No message
 * content, media bytes, or session material ever cross IPC on this VM — the
 * archive stays on disk and only file paths + counts are reported. The stream
 * emits `Running` batches as rows are written, then exactly one terminal batch.
 */
export type ExportProgressVm = { 
/**
 * The job id (also the cancel handle for `export_cancel`).
 */
exportId: number, 
/**
 * The current phase (`Running` until exactly one terminal batch).
 */
phase: ExportPhase, 
/**
 * How many logical messages (Markdown transcript entries) have been written
 * so far — the transcript-progress counter the UI shows.
 */
messagesWritten: number, 
/**
 * The total logical messages in scope when known (the scoped root count), or
 * `null` before it has been computed. Drives the progress bar's determinacy.
 */
totalMessages: number | null, 
/**
 * How many media items had their bytes copied into `media/` (best-effort).
 */
mediaCopied: number, 
/**
 * How many media items were skipped (unresolvable / uncached / no resolver) —
 * counted, never fatal; the link + metadata are still emitted.
 */
mediaSkipped: number, 
/**
 * The written output file paths, populated on the `Completed` batch (the JSON
 * and/or Markdown files under the scope subfolder). Empty on non-terminal /
 * cleaned-up batches.
 */
outputPaths: Array<string>, 
/**
 * A human-readable failure description on `Failed` (never content/secrets), or
 * `null` otherwise.
 */
error: string | null, };
