// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The terminal (or in-flight) phase of a running export job (Story 5.5).
 *
 * Streamed on [`ExportProgressVm::phase`]: `Running` for every progress batch,
 * then exactly one terminal batch — `Completed` on success, `Cancelled` when the
 * user cancelled (partial output cleaned), or `Failed` on an error (partial
 * output cleaned, `error` set). Serializes to its camelCase name.
 */
export type ExportPhase = "running" | "completed" | "cancelled" | "failed";
