// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The OS-global summon hotkey binding, projected to the Settings → Shortcuts
 * section (Story 9.4, FR-50).
 *
 * `accelerator` is the current opaque binding (e.g. `"Control+Alt+Space"`);
 * `isDefault` is whether it equals the shipped default; `active` is whether that
 * binding is currently registered with the OS (`false` ⇒ the section explains what to
 * enable rather than showing nothing); `conflict` carries a *soft* warning when the
 * accelerator matches a curated common macOS system shortcut (assignment still
 * proceeds), else `null`. The frontend renders this VM only — it never derives
 * conflict or registration state itself.
 */
export type HotkeyVm = { 
/**
 * The current accelerator string (opaque to the frontend; the shell parses it).
 */
accelerator: string, 
/**
 * Whether the current accelerator equals the shipped default (`⌃⌥Space`).
 */
isDefault: boolean, 
/**
 * Whether the accelerator is currently registered with the OS.
 */
active: boolean, 
/**
 * A soft conflict warning when the accelerator matches a curated macOS system
 * shortcut; `None` for a novel combo.
 */
conflict: string | null, };
