// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InboxRoomVm } from "./InboxRoomVm";

/**
 * One index-based merged-inbox operation mirroring an eyeball-im `VectorDiff`
 * (AD-8, AD-20).
 *
 * The merged inbox is computed in `keeper-core::inbox`; keeper streams its
 * recency-ordered result as these ops. The frontend applies them to a plain
 * array by index and **never** re-sorts. Serialized as an internally tagged
 * enum so the frontend can switch on `op`. The variants mirror [`RoomListOp`]
 * so the shared frontend diff reducer applies both.
 */
export type InboxOp = { "op": "reset", 
/**
 * The complete current merged window, in recency order.
 */
rooms: Array<InboxRoomVm>, } | { "op": "append", 
/**
 * Rooms to append.
 */
rooms: Array<InboxRoomVm>, } | { "op": "clear" } | { "op": "insert", 
/**
 * The insertion index.
 */
index: number, 
/**
 * The room to insert.
 */
room: InboxRoomVm, } | { "op": "set", 
/**
 * The index to overwrite.
 */
index: number, 
/**
 * The replacement room.
 */
room: InboxRoomVm, } | { "op": "remove", 
/**
 * The index to remove.
 */
index: number, };
