// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InboxOp } from "./InboxOp";

/**
 * A batch of merged-inbox ops delivered over the subscription's `Channel`
 * (AD-8, AD-20).
 *
 * The stream always opens with a batch whose first op is an [`InboxOp::Reset`]
 * carrying the current merged window, then further batches as accounts sync or
 * are added/removed. The merge is partitioned into an Inbox and an Archive
 * window (Story 4.2), and `total` is the length of *this* window's partition.
 */
export type InboxBatch = { 
/**
 * The ordered ops to apply, in sequence.
 */
ops: Array<InboxOp>, 
/**
 * The number of rooms in this streamed window (the partition's own length),
 * when known. Since Story 4.2 the merge is split into an Inbox and an
 * Archive window, so this is per-window, not a cross-account server total.
 */
total: number | null, };
