// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MuteState } from "./MuteState";

/**
 * A single merged-inbox room row, attributed to its owning account (AD-20).
 *
 * The unified inbox merges every active account's room-list stream into one
 * recency-ordered list. Each row is a [`RoomVm`]'s render data plus the opaque
 * keeper `accountId` it belongs to and that account's persisted `hueIndex`
 * (0–7). Carries **only** non-secret render data — no tokens, session material,
 * or event ids cross IPC on this VM. The frontend renders the hue as a 3 px
 * left edge bar and opens the row's timeline on the row's `accountId`.
 */
export type InboxRoomVm = { 
/**
 * Opaque keeper account id this room belongs to. Drives timeline/send.
 */
accountId: string, 
/**
 * The account's hue index (0–7) for the row's edge bar.
 */
hueIndex: number, 
/**
 * Opaque Matrix room id (passed through verbatim as a string).
 */
roomId: string, 
/**
 * The SDK-computed room display name.
 */
displayName: string, 
/**
 * Plain-text preview of the latest `m.room.message`, or `null`.
 */
lastMessage: string | null, 
/**
 * Latest-event timestamp: ms since the Unix epoch (UTC), or `null`.
 */
timestamp: number | null, 
/**
 * Optional room avatar URL (an `mxc://` URI), or `null`.
 */
avatarUrl: string | null, 
/**
 * Authoritative unread flag: `true` when the room has unread messages,
 * unread mentions, or the manual `m.marked_unread` flag set (AD-20). The
 * frontend renders this directly (bold name + dot/badge) and never
 * re-derives it from events.
 */
isUnread: boolean, 
/**
 * Count of unread mentions (client-side, precise for E2EE). Drives the
 * filled primary mention badge; a value of 0 shows a plain dot when
 * `is_unread` is otherwise set.
 */
mentionCount: number, 
/**
 * Authoritative archive flag: `true` when the room carries the Matrix
 * low-priority tag (`m.lowpriority`) (Story 4.2, AD-20). The merge
 * partitions on this to place the row in the Archive window unless it is
 * unread (auto-return is a pure view rule); the frontend never re-derives it.
 */
isArchived: boolean, 
/**
 * Authoritative favourite flag: `true` when the room carries the Matrix
 * favourite tag (`m.favourite`) (Story 4.4, AD-20). A *notable* tag, so a
 * change re-emits the room-list stream live and syncs cross-client (SDK-
 * sourced, copied through like `is_archived` — not merger-owned like
 * `is_pinned`). The merge partitions on this to place the row in the
 * Favorites window (removed from Inbox/Archive), behind Pins in precedence;
 * the frontend renders this directly (Favorite/Unfavorite gating) and never
 * re-derives it.
 */
isFavourite: boolean, 
/**
 * Authoritative pin flag: `true` when the room is pinned in keeper-local
 * state (Story 4.3, AD-20). Pins are keeper-local (no Matrix tag), owned by
 * the merger, which places a pinned room in the Pins window (removed from
 * Inbox/Archive). The frontend renders this directly (Pin/Unpin gating) and
 * never re-derives it.
 */
isPinned: boolean, 
/**
 * The bridged-Network label for this row (Story 4.6, FR-24), copied straight
 * through from [`RoomVm::network`]. `None` for a native Matrix room (no badge).
 * Drives the avatar Network badge and the ephemeral Network filter's retain;
 * the frontend renders the badge directly and never re-derives or re-filters it.
 */
network: string | null, 
/**
 * The room's stable bridge `network_id` — the machine `protocol.id` (Story 6.5,
 * FR-28), copied straight through from [`RoomVm::network_id`]. Distinct from the
 * display `network` label: this is the join key the frontend matches against an
 * unhealthy bridge session on `(account_id, network_id)` to show the affected-row
 * health dot and the in-conversation re-link banner. `None` for a native Matrix
 * room. Never re-derived on the frontend — it mirrors the Rust stream.
 */
networkId: string | null, 
/**
 * The durable per-Chat / per-Network mute intent (Story 10.2, FR-52), copied
 * straight through from [`RoomVm::mute_state`]. Drives the row's mute glyph
 * (`Muted` → bell-off, `MentionOnly` → at-sign); `None` shows no glyph. Reflects
 * durable mute only — never the global DND switch — and never gates unread.
 */
muteState: MuteState, };
