// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpcErrorCode } from "./IpcErrorCode";

/**
 * The single error envelope every fallible command rejects with (AD-8, AD-21).
 */
export type IpcError = { 
/**
 * Stable machine-readable error code.
 */
code: IpcErrorCode, 
/**
 * Human-readable message (never contains secrets or plaintext).
 */
message: string, 
/**
 * Opaque keeper account id this error pertains to, when applicable.
 */
accountId: string | null, 
/**
 * Whether retrying the same operation may succeed.
 */
retriable: boolean, };
