// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One labeled input field the bridge asked for during a code-entry login step
 * (Story 6.3, FR-26).
 *
 * A non-secret projection of a bridgev2 `user_input` field descriptor: the field
 * `id` the submit body is keyed by, its provisioning `field_type` (so the Sheet
 * can pick an input treatment — a segmented code input, a masked password, …), a
 * human `name`/`description`, an optional client-side validation `pattern`, and an
 * optional prefilled `default_value`. NO entered value or secret ever rides on
 * this VM — values travel only inside a [`BridgeLoginInput::Fields`] submit.
 */
export type LoginFieldVm = { 
/**
 * The field id the submit body is keyed by (opaque, passed through verbatim).
 */
id: string, 
/**
 * The provisioning field type (e.g. `"phone_number"`, `"2fa_code"`,
 * `"password"`, `"token"`, `"username"`), driving the input treatment.
 */
fieldType: string, 
/**
 * The human-readable field label (e.g. `"Phone number"`).
 */
name: string, 
/**
 * An optional longer description / helper text, or `null`.
 */
description: string | null, 
/**
 * An optional regex the entered value must match before submit (client-side
 * validated), or `null`.
 */
pattern: string | null, 
/**
 * An optional prefilled default value (non-secret), or `null`.
 */
defaultValue: string | null, };
