// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable login method the bridge offers (Story 6.3, FR-26).
 *
 * A non-secret projection of a bridgev2 login flow descriptor: the stable `id`
 * used to start the flow and a human `name`/`description` for the RadioGroup.
 */
export type LoginFlowVm = { 
/**
 * The stable flow id used to start this login method (opaque, verbatim).
 */
id: string, 
/**
 * The flow's human-readable name (e.g. `"QR code"`).
 */
name: string, 
/**
 * An optional longer description of the method, or `null`.
 */
description: string | null, };
