// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The durable per-Chat / per-Network mute intent stamped on a room row (Story
 * 10.2, FR-52, AD-18).
 *
 * A pure render signal computed at inbox emit time from the room's synced Matrix
 * push-rule mode plus the keeper-local muted-Network set: `Muted` when the room
 * mode is `RoomNotificationMode::Mute` **or** the room's bridged Network is in the
 * muted set; `MentionOnly` when the mode is `MentionsAndKeywordsOnly`; otherwise
 * `None`. It reflects *durable* mute intent only — it deliberately does **not**
 * reflect the global Do-Not-Disturb switch (shown once in the footer, never stamped
 * per row) and never gates unread. Fail-open: any read error resolves to `None`.
 * Serializes to `"none" | "muted" | "mention_only"` (the frontend wire contract).
 */
export type MuteState = "none" | "muted" | "mention_only";
