// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bridged Network connected in the merged inbox, surfaced as a filter view
 * (Story 4.6, FR-24, AD-20).
 *
 * Carries **only** the Network's display `name`, deduped by name across accounts —
 * a Network is identified cross-account by its label (a Telegram bridge on two
 * accounts is one Network row). Derived in the merger from the distinct non-`None`
 * [`RoomVm::network`] values of the unfiltered merged set (name-sorted, native
 * rooms excluded). The frontend renders a NETWORKS sidebar row per `NetworkVm`
 * and, on select, pokes the ephemeral Network filter identified by `name`.
 */
export type NetworkVm = { 
/**
 * The bridged Network's display name (the filter selection key).
 */
name: string, };
