// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of resolving a new-chat identifier through the bridge (Story 6.6,
 * FR-32).
 *
 * Carries only the non-secret portal `room_id` the frontend opens verbatim via
 * `roomsStore.selectRoom`. The account's Matrix access token is used only as an HTTP
 * Bearer header inside the provisioning transport and **never** appears here — no
 * token, cookie, or session material crosses IPC.
 */
export type NewChatResolutionVm = { 
/**
 * The resolved portal room id to open (opened verbatim, never inferred).
 */
roomId: string, };
