// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The click-through target carried by every native notification (Story 10.4, FR-51).
 *
 * Attached at the notification dispatch site so a click can land the user in the
 * right place. Under the **Option B** MVP scope (coordinator decision 2026-07-06) the
 * kept `tauri-plugin-notification` desktop backend has no per-notification click
 * callback, so the payload is recorded app-side as the "last notification target" at
 * dispatch and drives only a **coarse** view landing on app activation — Message
 * targets land on the Inbox, Bridge targets on the Bridges view. The full
 * `(account_id, room_id, event_id)` payload ships now even though MVP click handling is
 * coarse; exact-message / exact-re-login deep landing via a click-capable backend is
 * deferred to Epic 11 (see `deferred-work.md`). This is NEVER exact-message routing.
 *
 * Serialized as an internally tagged enum so the frontend can switch on `kind`.
 */
export type NotifyTarget = { "kind": "message", 
/**
 * The opaque keeper account id the message belongs to.
 */
accountId: string, 
/**
 * The Matrix room id the message was sent in.
 */
roomId: string, 
/**
 * The message's Matrix event id.
 */
eventId: string, } | { "kind": "bridge", 
/**
 * The opaque keeper account id owning the bridge session.
 */
accountId: string, 
/**
 * The stable machine `network_id` (the `protocol.id`) of the bridge.
 */
networkId: string, } | { "kind": "none" };
