// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeldSendVm } from "./HeldSendVm";

/**
 * A full snapshot of the held sends streamed to the frontend for one open Chat
 * (Story 8.3). The outbox stream is low-churn, so each change emits a fresh, complete
 * snapshot (oldest-first) that REPLACES the room's mirrored rows — the frontend store
 * never folds ops. Empty `rows` means the Chat currently has no held sends.
 */
export type OutboxVm = { 
/**
 * The held sends for the subscribed Chat, oldest-first.
 */
rows: Array<HeldSendVm>, };
