// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaletteActionVm } from "./PaletteActionVm";
import type { PaletteChatVm } from "./PaletteChatVm";

/**
 * The grouped, ranked, bounded result of one `palette_query` (Story 9.1).
 *
 * The single view model the palette renders. `contacts` holds matched direct/DM
 * rooms, `chats` holds matched non-DM rooms (a person is never in both), and
 * `actions` holds matched (or, on an empty/short/no-match query, top) registered
 * actions. All filtering, fuzzy scoring, and ranking happen in Rust — the
 * frontend only renders these three lists and dispatches by id; it never filters
 * or re-orders. Each list is capped to a bounded top-N so the render stays cheap.
 */
export type PaletteResultsVm = { 
/**
 * Matched direct/DM contact rows (empty for a short/no-match query).
 */
contacts: Array<PaletteChatVm>, 
/**
 * Matched non-DM chat rows (empty for a short/no-match query).
 */
chats: Array<PaletteChatVm>, 
/**
 * Matched actions, or the top registered actions on a short/no-match query.
 */
actions: Array<PaletteActionVm>, };
