// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which palette query mode the frontend requested (Story 9.1).
 *
 * `Default` filters chats + contacts (at ≥2 chars) plus matching actions;
 * `Action` (the `>`-prefix mode) returns only actions with open-chat-context
 * ranking. Serializes to its camelCase name — the `mode` argument of
 * `palette_query`.
 */
export type PaletteMode = "default" | "action";
