// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One action-kind result row from the command palette (Story 9.1).
 *
 * A projection of a single entry in the Rust action registry
 * (`keeper_core::palette::palette_actions`) — the sole source of palette actions,
 * reused by the cheat sheet + native menu bar (Story 9.3). Carries the stable
 * `id` (dispatched by the frontend `actions.ts` map), the human `title`, its
 * `category` group label, the `keywords` it also matches on, an optional
 * `shortcut` chip string (e.g. `"⌘K"`), and `requiresOpenChat` — `true` for an
 * action that operates on the currently open chat (Archive, Pin, …), which the
 * frontend disables when no chat is open and which ranks first in action mode
 * when a chat is open. Static, non-secret render data only.
 */
export type PaletteActionVm = { 
/**
 * Stable action id — the dispatch key the frontend maps to a handler.
 */
id: string, 
/**
 * The human-readable action title (the row label).
 */
title: string, 
/**
 * The action's category / group label (e.g. `"Navigation"`, `"Chat"`).
 */
category: string, 
/**
 * Extra keywords the action also matches on (never rendered directly).
 */
keywords: Array<string>, 
/**
 * An optional shortcut-chip string (e.g. `"⌘K"`), or `None` when unbound.
 */
shortcut: string | null, 
/**
 * `true` when the action operates on the currently open chat.
 */
requiresOpenChat: boolean, 
/**
 * `true` when the action requires the `recording` capability (Story 16.3):
 * the shell filters it out of the palette, cheat sheet, and native menu when
 * screen recording is unavailable, so a recording action is absent (never a
 * dead button) on platforms that cannot record.
 */
requiresRecording: boolean, 
/**
 * The toggle-pair group this action belongs to (Story 9.3), e.g. `"archive"`
 * for both `archive-chat` and `unarchive-chat`. `None` for a non-toggle action.
 * The palette ignores this (backward-safe); the cheat sheet + native menu
 * collapse each group's two actions into a single unambiguous entry.
 */
toggleGroup: string | null, };
