// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response of the `app_ping` liveness command.
 */
export type PingVm = { 
/**
 * Backend liveness marker, e.g. `"pong"`.
 */
message: string, 
/**
 * Server-side timestamp: milliseconds since the Unix epoch (UTC).
 *
 * Emitted to TypeScript as `number`, not `bigint`: Tauri IPC delivers the
 * `i64` as a JS number via `JSON.parse`, and ms-epoch values stay well
 * within `Number.MAX_SAFE_INTEGER`. This keeps the binding matching the
 * wire reality — the timestamp convention every later VM copies.
 */
ts: number, };
