// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recordable audio/video device (microphone or camera) reported by
 * `listSources` (Story 16.4): a flat `{id, name}` row — the `localizedName`
 * already distinguishes built-in / external / Continuity devices, so there
 * is deliberately no device-class field. Microphones enumerate live since
 * Story 19.3, cameras since Story 20.1.
 */
export type RecordingDeviceVm = { 
/**
 * The device's unique identifier.
 */
id: string, 
/**
 * The human-readable device name.
 */
name: string, };
