// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordingApplicationVm } from "./RecordingApplicationVm";
import type { RecordingDeviceVm } from "./RecordingDeviceVm";
import type { RecordingDisplayVm } from "./RecordingDisplayVm";

/**
 * The `listSources` result (Story 16.4, AD-34): everything the sidecar can
 * currently offer as a capture source — real displays (CoreGraphics), real
 * applications (SCShareableContent, Story 19.1), real microphones (Story
 * 19.3) and real cameras (Story 20.1) via AVFoundation.
 */
export type RecordingSourcesVm = { 
/**
 * The active displays (real, from the sidecar's display enumeration).
 */
displays: Array<RecordingDisplayVm>, 
/**
 * Recordable applications (real since Story 19.1).
 */
applications: Array<RecordingApplicationVm>, 
/**
 * Microphone devices (real since Story 19.3).
 */
microphones: Array<RecordingDeviceVm>, 
/**
 * Camera devices (real since Story 20.1) — a flat name list for the
 * Webcam card's picker.
 */
cameras: Array<RecordingDeviceVm>, };
