// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recordable application reported by `listSources` (Story 16.4/19.1). Real
 * enumeration lands in Story 19.1 via the sidecar's `SCShareableContent`
 * enumeration: keeper's own bundle id is excluded (it can never be a target),
 * apps that own no on-screen window are dropped, and the list is name-sorted.
 */
export type RecordingApplicationVm = { 
/**
 * The application bundle identifier.
 */
bundleId: string, 
/**
 * The human-readable application name.
 */
name: string, 
/**
 * The running process id.
 */
pid: number, 
/**
 * The app's icon as a bounded (≤64×64px) PNG `data:image/png;base64,…`
 * URI (Story 19.1), or `None` when an icon can't be produced — the picker
 * then falls back to a generic app glyph. Kept small so the polled list
 * never becomes a large-payload-over-IPC violation.
 */
icon: string | null, };
