// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recordable display reported by `listSources` (Story 16.4, AD-34) — real
 * values from the sidecar's active-display enumeration.
 */
export type RecordingDisplayVm = { 
/**
 * The CoreGraphics display id (stable for the session, not across reboots).
 */
id: number, 
/**
 * The display width in points.
 */
width: number, 
/**
 * The display height in points.
 */
height: number, 
/**
 * Whether this is the main display (menu-bar display).
 */
isMain: boolean, 
/**
 * The display's true pixel width (Story 22.1; additive — 0 when an older
 * sidecar omits it). Backs the live effective-resolution hint.
 */
pixelWidth: number, 
/**
 * The display's true pixel height (Story 22.1; additive — 0 when absent).
 */
pixelHeight: number, };
