// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The UI-facing state of the (at most one) live recording session (Story 16.6,
 * AD-33). A plain string projection of `keeper_core::recording::SessionState`
 * plus `idle` for "no session yet this app lifetime". Serializes to
 * `"idle" | "preflight" | "recording" | "rotating" | "stopping" | "finalized" |
 * "recovered" | "failed"`.
 */
export type RecordingUiState = "idle" | "preflight" | "recording" | "rotating" | "stopping" | "finalized" | "recovered" | "failed";
