// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The capture feature flags the `keeper-rec` sidecar reports via `getCapabilities`
 * (Story 16.4, AD-34). Shape-locked; values are code-owned and honest about what
 * the sidecar build actually supports today.
 */
export type RecordingFeaturesVm = { 
/**
 * Whether system-audio capture is supported (true on the macOS 13+ sidecar).
 */
systemAudio: boolean, 
/**
 * Whether microphone capture is supported (live since Story 19.3).
 */
microphone: boolean, 
/**
 * Whether camera/webcam capture is supported (live since Story 20.1 — a
 * separate `camera-####.mp4` per segment, never a track inside the
 * screen file).
 */
camera: boolean, };
