// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The remote (cross-device) draft read back from the account-data mirror for a
 * `(account, room)` (Story 7.2, AD-15). Returned by `load_remote_draft` and
 * carried in a [`DraftMirrorBatch`] on a live remote edit.
 *
 * **Local always wins**: this is only ever read to *offer* adoption. `body` is
 * always non-empty here — an empty body reads back as "no remote draft"
 * (`None`), so a tombstone never surfaces as an adoptable draft. `updated_ts` is
 * informational/forward-scaffolding only; the winner rule is purely local-wins
 * and never consults a timestamp. The body is never logged.
 */
export type RemoteDraftVm = { 
/**
 * The remote draft body (always non-empty; empty maps to `None`).
 */
body: string, 
/**
 * Write time in milliseconds since the Unix epoch (UTC). Informational only.
 */
updatedTs: number, };
