// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The data-driven risk tier of a bridged Network (Story 6.1, Epic 6 addendum
 * §2).
 *
 * Sourced from `risk-tiers.json` — never hardcoded in TypeScript. Only the four
 * *surfaced* tiers cross IPC: the out-of-scope tier stays in the data file for
 * completeness but is excluded from the catalog and has no enum variant.
 * Serializes to its camelCase name — the frontend wire contract.
 */
export type RiskTier = "low" | "maintenance" | "volatile" | "conditional";
