// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomListOp } from "./RoomListOp";

/**
 * A batch of room-list ops delivered over the subscription's `Channel` (AD-8).
 *
 * The stream always opens with a batch whose first op is a
 * [`RoomListOp::Reset`] carrying the current window, then diff batches.
 */
export type RoomListBatch = { 
/**
 * The ordered ops to apply, in sequence.
 */
ops: Array<RoomListOp>, 
/**
 * The total number of rooms the server knows about, when known.
 */
total: number | null, };
