// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MuteState } from "./MuteState";

/**
 * A single room row rendered in the chat list (FR-8, NFR-9, AD-20).
 *
 * Carries **only** non-secret render data. `timestamp` is `i64` milliseconds
 * since the Unix epoch (UTC) — never an ISO string. `lastMessage` is the
 * plain-text body of the room's latest event when it is an `m.room.message`
 * (text/notice/emote); `null` for any other event kind. No tokens, session
 * material, or event ids cross IPC on this VM.
 */
export type RoomVm = { 
/**
 * Opaque Matrix room id (passed through verbatim as a string).
 */
roomId: string, 
/**
 * The SDK-computed room display name.
 */
displayName: string, 
/**
 * Plain-text preview of the latest `m.room.message`, or `null`.
 */
lastMessage: string | null, 
/**
 * Latest-event timestamp: ms since the Unix epoch (UTC), or `null`.
 */
timestamp: number | null, 
/**
 * Optional room avatar URL (an `mxc://` URI), or `null`.
 */
avatarUrl: string | null, 
/**
 * Authoritative unread flag: `true` when the room has unread messages,
 * unread mentions, or the manual `m.marked_unread` flag set (AD-20). The
 * frontend renders this directly (bold name + dot/badge) and never
 * re-derives it from events.
 */
isUnread: boolean, 
/**
 * Count of unread mentions (client-side, precise for E2EE). Drives the
 * filled primary mention badge; a value of 0 shows a plain dot when
 * `is_unread` is otherwise set.
 */
mentionCount: number, 
/**
 * Authoritative archive flag: `true` when the room carries the Matrix
 * low-priority tag (`m.lowpriority`) (Story 4.2, AD-20). The inbox merge
 * partitions on this to place the room in the Archive window unless it is
 * unread (auto-return is a pure view rule); the frontend never re-derives it.
 */
isArchived: boolean, 
/**
 * Authoritative favourite flag: `true` when the room carries the Matrix
 * favourite tag (`m.favourite`) (Story 4.4, AD-20). This is a *notable* tag,
 * so a change re-emits the room-list stream live and syncs cross-client. The
 * inbox merge partitions on this to place the room in the Favorites window
 * (removed from Inbox/Archive); the frontend never re-derives it.
 */
isFavourite: boolean, 
/**
 * Whether the room is itself a Matrix Space (`Room::is_space()`, `m.space`
 * room type) (Story 4.5, AD-20). Used only to *exclude* Space rooms from the
 * four inbox chat windows in the merge — Spaces are containers, not chats, and
 * are surfaced separately as filter views. Not copied to [`InboxRoomVm`]; the
 * merge drops `is_space` rooms before partitioning.
 */
isSpace: boolean, 
/**
 * The bridged-Network label for this room (Story 4.6, FR-24), resolved from
 * the room's MSC2346 `m.bridge` (or legacy `uk.half-shot.bridge`) state via
 * [`crate::bridge::room_bridge_network`] — "Telegram", "WhatsApp", "Signal", …
 * `None` for a native Matrix room (no bridge state); it then shows no badge and
 * is excluded from the distinct-Networks list. Copied through to
 * [`InboxRoomVm`] and used both for the avatar Network badge and the ephemeral
 * Network filter. Never fabricated — it is untrusted, length-capped state.
 */
network: string | null, 
/**
 * The room's stable bridge `network_id` — the machine `protocol.id` (Story 6.5,
 * FR-28), resolved from the room's MSC2346 `m.bridge` state via
 * [`crate::bridge::room_bridge_protocol_id`] (e.g. `"whatsapp"`, `"telegram"`).
 * Distinct from the display `network` label: this is the join key that matches a
 * room to an unhealthy bridge session on `(account_id, network_id)`. `None` for a
 * native Matrix room (no bridge state). Copied through to [`InboxRoomVm`]. Never
 * fabricated — it is untrusted, server-controlled state used only as a map key.
 */
networkId: string | null, 
/**
 * The durable per-Chat / per-Network mute intent for this room (Story 10.2,
 * FR-52), resolved at projection time from the room's synced push-rule mode plus
 * the keeper-local muted-Network set. Copied through to [`InboxRoomVm`] to render
 * the mute glyph; never gates unread. Fail-open `None` on any read error.
 */
muteState: MuteState, };
