// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The honest Screen Recording tri-state the permission pre-flight resolves
 * (Story 16.5, Epic 16, FR-67, AD-36).
 *
 * The sidecar's non-prompting preflight is two-valued ([`TccPermission`]:
 * `Granted` vs `NotDetermined`) — it cannot tell an explicit denial from a
 * never-requested state. `keeper_core::recording::resolve_screen_recording_access`
 * lifts it into this tri-state with a host *session* "already requested this app
 * lifetime" flag (one real OS prompt per app lifetime; the flag never persists
 * across sessions, so a grant is never cached optimistically). Serializes to
 * `"granted" | "notYetRequested" | "denied"`.
 */
export type ScreenRecordingAccess = "granted" | "notYetRequested" | "denied";
