// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One archive search result crossing IPC out of the `search_archive` command
 * (Story 5.3, FR-34).
 *
 * Carries the `(account_id, room_id, event_id)` deep-link identifiers the epic AC
 * mandates for jumping into a timeline at the matched message, plus render data:
 * sender, the matched display body, its timestamp, and whether the row is
 * redacted. `eventId` is the chain root (the edit target when the match was on a
 * prior version, else the row's own event id), so every version deep-links to the
 * same timeline item. This `eventId` is the epic-authorized search-scoped
 * exception to the no-ids rule (see the Story 5.3 design notes) — no tokens,
 * session material, or full event content beyond the display body crosses here.
 */
export type SearchHitVm = { 
/**
 * Opaque keeper account id the matched message belongs to.
 */
accountId: string, 
/**
 * Matrix room id the matched message was sent to.
 */
roomId: string, 
/**
 * The chain-root Matrix event id — the sanctioned deep-link handle.
 */
eventId: string, 
/**
 * Matrix user id of the sender.
 */
sender: string, 
/**
 * The matched display body (an edit's `m.new_content.body`, else the
 * original's top-level `body`).
 */
body: string, 
/**
 * The matched row's origin server timestamp: ms since the Unix epoch (UTC).
 */
timestamp: number, 
/**
 * `true` when the matched row has been marked remotely redacted. Only ever
 * `true` in results when the honor-deletions setting is off (when on, redacted
 * rows are excluded entirely).
 */
redacted: boolean, };
