// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The delivery state of an outgoing (local-echo) message (FR-9, AD-13, UX-DR10).
 *
 * Derived from the SDK `EventSendState` of a local echo: a message being
 * enqueued or retried is `Sending`; a message the server acknowledged is
 * `Sent`; a message whose send failed unrecoverably is `Failed`. A remote
 * (received or reconciled) item has no send state and maps to `None` on the VM.
 * Only the enum tag crosses IPC — never the txn id, error object, or event id.
 */
export type SendState = "sending" | "sent" | "failed";
