// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one manual sync did.
 *
 * Both the raw counts and the sentence composed from them, for the same
 * reason [`SyncStatusVm`] carries both: the Sync view and the Settings row
 * render the sentence verbatim, so the two surfaces cannot word one result
 * two different ways, and a caller that wants to branch on the numbers still
 * can.
 */
export type SyncOutcomeVm = { committed: boolean, pushed: boolean, pulled: boolean, filesChanged: number, conflicts: Array<string>, 
/**
 * Bytes this run moved over the network — the received pack plus every
 * LFS object transferred. Zero for a pass that found nothing to do, which
 * is the common and correct answer, never an error.
 */
bytes: number, 
/**
 * One sentence naming what happened, ready to render. See
 * [`outcome_line`].
 */
line: string, };
