// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A unit of work that failed permanently and stopped being retried.
 */
export type SyncParkedVm = { id: number, kind: string, attempts: number, lastError: string | null, };
