// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a profile is doing right now — the polled snapshot the tray reads.
 */
export type SyncStatusVm = { profileId: string, profileName: string, 
/**
 * `idle` | `watching` | `syncing` | `offline` | `mediaAbsent` | `paused` |
 * `needsAttention`.
 */
state: string, 
/**
 * `scanning` | `fetching` | … | `idle`.
 */
phase: string, 
/**
 * The single line the tray shows, composed in Rust so the tray and the
 * window can never word it differently.
 */
line: string, filesDone: number, filesTotal: number | null, bytesDone: number, bytesTotal: number | null, pending: number, 
/**
 * Files the completeness gate is holding inside their quiescence window.
 *
 * Distinct from `pending`, which counts journal rows: a folder where a
 * thousand files are still being written has none of those, so `pending`
 * alone reported it as up to date (AD-34-10). `line` already says this in
 * words; the number is here so a surface can show it without parsing prose.
 */
settling: number, 
/**
 * Sticky, last-write-wins, cleared only by a clean run — the same shape as
 * `RecordingStatusVm::warning` so the banner behaves identically.
 */
warning: string | null, error: string | null, lastSyncMs: number | null, 
/**
 * Whether this condition needs a human before the profile can progress.
 * Drives the split between a passive amber line and an actionable notice.
 */
needsAttention: boolean, };
