// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many rows a folder card's lists show, folded and unfolded.
 *
 * One pair for every list on the card rather than one pair per list: a user
 * setting this is answering "how much of this card do I want to read", and three
 * separate controls for one intent is how a settings pane stops being usable.
 *
 * The setter clamps (folded `1..=50`, unfolded `10..=1000`) and returns the
 * effective VM, so the UI never shows an unsaved value; `unfolded` is also read
 * as never less than `folded`, because two independent rows can otherwise store
 * an "unfold" that reveals fewer rows than the fold it opened.
 */
export type SyncListSettingsVm = { 
/**
 * Rows visible before unfolding (default 10).
 */
folded: number, 
/**
 * Rows visible after unfolding (default 100). Also the `LIMIT` the activity
 * query runs with, so it bounds what the card can show at all.
 */
unfolded: number, };
