// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A macOS TCC (privacy database) permission state as reported by the `keeper-rec`
 * sidecar (Story 16.4, Epic 16, AD-34).
 *
 * The sidecar is the process that will capture (16.6), so *its* grant is the one
 * that matters. In this story only `screenRecording` is probed live (a
 * non-prompting CoreGraphics preflight in the sidecar); `microphone`/`camera` stay
 * provisional `NotDetermined` until AVFoundation detection lands (16.6/19). The
 * preflight is two-valued, so it only reports `Granted` vs `NotDetermined` — it
 * cannot distinguish an explicit `Denied` from a never-requested state. The
 * authoritative granted / not-yet-requested / denied tri-state and its live
 * pre-flight UI (request, deep-link, re-detection) are Story 16.5's. Serializes
 * to `"granted" | "denied" | "notDetermined"`.
 */
export type TccPermission = "granted" | "denied" | "notDetermined";
