// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineItemVm } from "./TimelineItemVm";

/**
 * One index-based timeline operation mirroring an eyeball-im `VectorDiff`
 * (AD-8, AD-9, AD-20).
 *
 * The SDK `Timeline`'s `subscribe` stream yields a `VectorDiff` sequence;
 * keeper forwards it verbatim as these ops (one VM per SDK item). The frontend
 * applies them to a plain array by index and **never** re-sorts, filters, or
 * re-indexes. Serialized as an internally tagged enum so the frontend can
 * switch on `op`.
 */
export type TimelineOp = { "op": "reset", 
/**
 * The complete current timeline, in order.
 */
items: Array<TimelineItemVm>, } | { "op": "append", 
/**
 * Items to append.
 */
items: Array<TimelineItemVm>, } | { "op": "clear" } | { "op": "pushFront", 
/**
 * The item to prepend.
 */
item: TimelineItemVm, } | { "op": "pushBack", 
/**
 * The item to append.
 */
item: TimelineItemVm, } | { "op": "popFront" } | { "op": "popBack" } | { "op": "insert", 
/**
 * The insertion index.
 */
index: number, 
/**
 * The item to insert.
 */
item: TimelineItemVm, } | { "op": "set", 
/**
 * The index to overwrite.
 */
index: number, 
/**
 * The replacement item.
 */
item: TimelineItemVm, } | { "op": "remove", 
/**
 * The index to remove.
 */
index: number, } | { "op": "truncate", 
/**
 * The new length.
 */
length: number, };
