// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypistVm } from "./TypistVm";

/**
 * A batch delivered over the typing subscription's `Channel` (Story 3.9, AD-8,
 * AD-14).
 *
 * The full current set of *other* members typing in the open room — inherently
 * idempotent, safe to re-subscribe. An empty `typists` means nobody is typing
 * (the frontend renders nothing). The stream opens with the current set, then
 * emits on every change.
 */
export type TypingBatch = { 
/**
 * The members currently typing (other than the account's own user).
 */
typists: Array<TypistVm>, };
