// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SasEmojiVm } from "./SasEmojiVm";
import type { VerificationPhase } from "./VerificationPhase";

/**
 * A snapshot of an interactive self-verification flow, delivered over the
 * verification subscription's `Channel` (Story 3.2, FR-14, AD-1, NFR-9).
 *
 * The single view model the webview renders for the whole flow. Carries **only**
 * non-secret render data: the opaque `flow_id`, the current [`VerificationPhase`],
 * the SAS emoji list (symbols + names) when comparing, a pre-rendered QR SVG
 * string when a QR is available, and a human `reason` on cancel/failure. NO
 * `Verification`/`Sas`/`QrVerification` object, SAS key, decimal, or plaintext
 * ever crosses IPC on this VM (AD-1). Actions reference the flow by `flow_id`.
 */
export type VerificationFlowVm = { 
/**
 * The SDK verification flow id (opaque, passed through verbatim). Actions
 * (accept/start_sas/confirm/mismatch/cancel) reference the flow by this id.
 */
flowId: string, 
/**
 * The current flow phase.
 */
phase: VerificationPhase, 
/**
 * The 7 SAS emoji to compare, present only in the `Comparing` phase.
 */
emojis: Array<SasEmojiVm> | null, 
/**
 * A pre-rendered QR-code SVG string (keeper's own QR for the peer to scan),
 * present when a QR is available in the `Ready` phase.
 */
qrCodeSvg: string | null, 
/**
 * A human-readable reason, present on `Cancelled` / `Failed`.
 */
reason: string | null, };
