// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The phase of an interactive self-verification flow (Story 3.2, FR-14,
 * UX verification-flow states).
 *
 * A Rust-authoritative projection of the SDK's native `VerificationRequestState`
 * / `SasState` machine. The webview renders each phase distinctly (waiting,
 * comparing, confirmed, done, cancelled, failed) using the SDK's own vocabulary —
 * it never invents crypto UX. Only the enum tag crosses IPC. `Cancelled` and
 * `Failed` are intentionally distinct: a clean user/peer cancel is `Cancelled`;
 * a mismatch / timeout / other terminal cancel code is `Failed` (with a reason).
 */
export type VerificationPhase = "requested" | "ready" | "comparing" | "confirmed" | "done" | "cancelled" | "failed";
